// <auto-generated />
namespace Project_Bike_Hikes.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class FieldToProperty : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FieldToProperty));
        
        string IMigrationMetadata.Id
        {
            get { return "202604141159421_FieldToProperty"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
